### ISSUE TITLE
jasp vs vaspy on gilgamesh

### ISSUE THREAD

**Issue by devonwa** [jkitchin/vasp#12]
Can vasp handle jobs previously run by jasp? If so, I think there's a server implementation issue on gilgamesh.

This works:
```python
from ase import Atoms, Atom
from jasp import *

with jasp('~/dft-book/molecules/simple-co') as calc:
    atoms = calc.get_atoms()
```

This doesn't:
```python
from ase import Atoms, Atom
from vasp import Vasp

print(Vasp.default_parameters) # this works.

calc = Vasp('~/dft-book/molecules/simple-co') # breaks here
atoms = calc.get_atoms()
```

Trace:
```shell
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 45, in inner
    return func(self, *args, **kwargs)
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp_core.py", line 242, in __init__
    str(label), atoms)
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/opt/kitchingroup/vasp-5.3.5/ase-s16/ase/calculators/calculator.py", line 513, in __init__
    atoms, **kwargs)
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/opt/kitchingroup/vasp-5.3.5/ase-s16/ase/calculators/calculator.py", line 184, in __init__
    self.read(restart)  # read parameters, atoms and results
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/readers.py", line 322, in read
    atoms = self.read_atoms()
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/opt/kitchingroup/vasp-5.3.5/vaspy/vasp/readers.py", line 249, in read_atoms
    atoms.positions = xatoms.positions[resort]
AttributeError: 'NoneType' object has no attribute 'positions'
```

**Comment by jkitchin** [comment]
no. it can't.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by devonwa** [comment]
Oh, that might be it. Closed.
