### ISSUE TITLE
Weird Exception Handler Issue

### ISSUE THREAD

**Issue by prtkm** [jkitchin/vasp#19]
Hi John,

I am finally switching from jasp to vasp.py. I seem to be seeing this weird error when I first run a calculation and I cant seem to figure out why it gets raised. The calculation seems to be running fine, and the second time I run it I get no errors. Any ideas about what is going on? 
@jboes Maybe you know?

```python
#+BEGIN_SRC python
from ase import Atoms, Atom
from vasp import Vasp

co = Atoms([Atom('C', [0, 0, 0]),
            Atom('O', [1.2, 0, 0])],
           cell=(6., 6., 6.))

calc = Vasp('molecules/simple-co',  # output dir
            xc='pbe',  # the exchange-correlation functional
            nbands=6,    # number of bands
            encut=350,    # planewave cutoff
            ismear=1,    # Methfessel-Paxton smearing
            sigma=0.01,  # very small smearing factor for a molecule
            atoms=co)
#print calc.implemented_properties
#print('energy = {0} eV'.format(co.get_potential_energy()))
#print(co.get_forces())
#+END_SRC
```
```
#+RESULTS:
: Unhandled exception in Vasp
: Traceback (most recent call last):
:   File "/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp.py", line 48, in inner
:     return func(self, *args, **kwargs)
:   File "/afs/crc.nd.edu/user/p/pmehta1/ase/ase/calculators/calculator.py", line 388, in get_property
:     raise NotImplementedError
: NotImplementedError
```

**Comment by jkitchin** [comment]
What version of ase are you using? I wasn't able to reproduce this with 3.12.0b1.

**Comment by prtkm** [comment]
I was afraid you wouldn't be able to. I am also using 3.12.0b1. I tried with your master branch (so it doesn't have any of the changes I made for the scheduler) and get the same error. The error only appears the first time the script is run, and the files don't already exist. I can't really infer from the the Traceback which line in Vasp is causing the error.

**Comment by jkitchin** [comment]
can you try setting debug=True in your calculator? I think that will bypass the exception handler.

**Comment by prtkm** [comment]
So here is some output by setting debug=True in the above code. I think the same message is printed  out 8 times because there is probably some parallelization going on on the login node.

```
#+begin_example
3.12.0b1
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/readers.py::268][read]]: Reading /afs/crc.nd.edu/user/p/pmehta1/dft-book/molecules/simple-co
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/readers.py::348][read_results]]: state: 0. Reading results in /afs/crc.nd.edu/user/p/pmehta1/dft-book/molecules/simple-co.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/setters.py::29][set]]: Setting {}
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/setters.py::29][set]]: Setting {'kpts': [1, 1, 1], 'xc': 'pbe', 'pp': 'PBE', 'encut': 350, 'lcharg': False, 'nbands': 6, 'ismear': 1, 'lwave': False, 'sigma': 0.01}
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::576][check_state]]: atoms IMM: [ 0.  0.]
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::583][check_state]]: FileIOCalculator reports these changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::640][check_state]]: System changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::576][check_state]]: atoms IMM: [ 0.  0.]
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::583][check_state]]: FileIOCalculator reports these changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::640][check_state]]: System changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::576][check_state]]: atoms IMM: [ 0.  0.]
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::583][check_state]]: FileIOCalculator reports these changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::640][check_state]]: System changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::576][check_state]]: atoms IMM: [ 0.  0.]
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::583][check_state]]: FileIOCalculator reports these changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::640][check_state]]: System changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::576][check_state]]: atoms IMM: [ 0.  0.]
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::583][check_state]]: FileIOCalculator reports these changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::640][check_state]]: System changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::576][check_state]]: atoms IMM: [ 0.  0.]
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::583][check_state]]: FileIOCalculator reports these changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::640][check_state]]: System changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::576][check_state]]: atoms IMM: [ 0.  0.]
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::583][check_state]]: FileIOCalculator reports these changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::640][check_state]]: System changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::576][check_state]]: atoms IMM: [ 0.  0.]
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::583][check_state]]: FileIOCalculator reports these changes: []
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/runner.py::40][in_queue]]: jobid not found for calculation.
DEBUG    [[/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp_core.py::640][check_state]]: System changes: []
#+end_example
```

If I actually do a calculation by uncommenting the line 
```
# print('energy = {0} eV'.format(co.get_potential_energy()))
```

with debug=True, I get the VaspSubmitted Exception (similar to what I used to with jasp). Without debug=True, I get this.

```
Unhandled exception in Vasp
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase/ase/calculators/calculator.py", line 388, in get_property
    raise NotImplementedError
NotImplementedError
Unhandled exception in Vasp
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase/ase/calculators/calculator.py", line 388, in get_property
    raise NotImplementedError
NotImplementedError
Unhandled exception in Vasp
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase/ase/calculators/calculator.py", line 388, in get_property
    raise NotImplementedError
NotImplementedError
/afs/crc.nd.edu/user/p/pmehta1/dft-book/molecules/simple-co submitted: 234189
energy = None eV
```

Also, this shouldn't be related python versions (2 v 3), right? I am on python 2.7.12

**Comment by jkitchin** [comment]
I feel like this is probably related to charges. It seems to be some property that it is trying to get that doesn't seem to be implemented.

**Comment by prtkm** [comment]
Ok. Got it! So 'free_energy' got pushed into ase a while ago as a property. If I comment that out, it seems to work as expected.

https://gitlab.com/ase/ase/commit/513bc91cf6579accb29bddd162b8a6bb66e785aa

I guess we should probably add free_energy as a property to vasp and set it to None somewhere.

**Comment by jkitchin** [comment]
I think this is fixed in 8c91280

**Comment by prtkm** [comment]
Looks good!

**Comment by tygao** [comment]
Hi Professor Kitchin,
It seems the same error happened to me today. The OURCAR file finished with total energy and forces, but there is this unhandled exception.

**Comment by jkitchin** [comment]
I just updated vaspy on the cluster. see if that fixed it. It shouldn't
have been an issue though, unless you updated ase somehow.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
That actually looks like a different error, where for some reason it doesn't seem to have a calculator. That should be unrelated to the free_energy property...

**Comment by jkitchin** [comment]
@tygao can you send me the path to that calculation?

**Comment by tygao** [comment]
@jkitchin "tianyug1/Research/Bulk/NDFT/surface=fcc111/type=md/order=md1/v_a=0_20/MD=136"

**Comment by jkitchin** [comment]
There seems to be some garbage in the OUTCAR that is probably causing a parsing error. 

1. Have you tried deleting the directory and rerunning the calculation?
2. Did this happen in other calculations too?
