### ISSUE TITLE
atoms_sorted issue

### ISSUE THREAD

**Issue by arosen93** [jkitchin/vasp#42]
I am trying to run your VASP interface with ASE and am getting the following issue: AttributeError: 'Vasp' object has no attribute 'atoms_sorted'. The traceback is shown below. I am using the newest version of ASE, so perhaps this is a recent change that conflicts with your interface? I could also just be doing something wrong since I haven't used your interface before. Any suggestions?

```
Traceback (most recent call last):
  File "sp_energy.py", line 12, in <module>
    e = isobutane.get_potential_energy()
  File "/home/asr731/software/ase/ase/atoms.py", line 682, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/home/asr731/software/ase/ase/calculators/calculator.py", line 441, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/home/asr731/software/ase/ase/calculators/calculator.py", line 486, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/home/asr731/software/kitchin_vasp/vasp/runner.py", line 94, in calculate
    self.write_input(atoms, properties, system_changes)
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/home/asr731/software/kitchin_vasp/vasp/writers.py", line 23, in write_input
    self.write_poscar()
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 51, in inner
    return self.exception_handler(self, *sys.exc_info())
  File "/home/asr731/software/kitchin_vasp/vasp/vasp.py", line 48, in inner
    return func(self, *args, **kwargs)
  File "/home/asr731/software/kitchin_vasp/vasp/writers.py", line 150, in write_poscar
    self.atoms_sorted,
AttributeError: 'Vasp' object has no attribute 'atoms_sorted'
```

**Comment by jkitchin** [comment]
hm. I haven't seen this. I am on sabbatical now, away from CMU, it could take a while to figure it out. Could you send me a small example script that leads to this error? Thanks.

**Comment by arosen93** [comment]
Surely. It seems really any minimal example will lead to this error. I don't _think_ I'm setting up the job wrong, but since it's the first time I'm using this calculator interface so I won't rule that out.  I am using the most recent version of ASE so I wonder if older versions will work fine. I'll report back here when I try that. The scheduler I use is MOAB, so I am running the calculator without the job management features as suggested [here](https://github.com/jkitchin/vasp/issues/40).

```
from vasp import Vasp
from ase.build import molecule
from vasp.vasprc import VASPRC
#VASPRC['mode'] = 'run'
#VASPRC['vasp.executable.serial'] = '/home/asr731/bin/submit_scripts/vasprc_script.py'

isobutane = molecule('isobutane')
isobutane.center()

calc = Vasp('mycalc',xc='PBE')
isobutane.set_calculator(calc)
e = isobutane.get_potential_energy()
print(e)
```

**Comment by jkitchin** [comment]
I think part of the problem is you should write your script like this:

```
from vasp import Vasp
from ase.build import molecule

isobutane = molecule('isobutane')
isobutane.set_cell((10, 10, 10))
isobutane.center()

calc = Vasp('mycalc',xc='PBE', atoms=isobutane)

e = isobutane.get_potential_energy()
print(e)
```

That eliminates the error you reported, and runs the job for me, but for some reason it also triggers a rerun on each time you run the script, which I think it should not be doing.

**Comment by arosen93** [comment]
Ah, yes. Apologies for that careless mistake. I forgot to change the way the `atoms` object is assigned to the calculator when copying my original ASE script. I have to now figure out a few other error messages but I'll figure it out in due time. Thanks again. You can close this issue depending on if you wish to fix the issue related to the script rerunning.
