### ISSUE TITLE
Package Install Problems

### ISSUE THREAD

**Issue by XinyuuLi** [jkitchin/vasp#46]
I installed vasp in a cluster by first run setup.py, followed by clone the repo to ~/jkitchin-python. However, when I call 'from vasp import Vasp', a error occured as:
` Traceback (most recent call last):
  File "script.py", line 2, in <module>
    from vasp import Vasp
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 24, in <module>
    import writers
  File "/home/c3289/kitchin-python/vasp/writers.py", line 17, in <module>
    def write_input(self, atoms=None, properties=None, system_changes=None):
  File "/home/c3289/kitchin-python/vasp/monkeypatch.py", line 16, in decorato                                                                             r
    func.__doc__ += s.format(f=func)
AttributeError: 'function' object has no attribute 'func_code'
`
Does this means I made mistakes in install this package?

Thanks.

**Comment by jkitchin** [comment]
Are you using python2 or 3?

**Comment by XinyuuLi** [comment]
Hi John. I am using python 3. In https://github.com/jkitchin/vasp/issues/33, prtkn said most things work on python3. Is python3 still unsupported?

**Comment by jkitchin** [comment]
The master branch is for python2. you can try checking out the Python3 branch. Some people have reported it works.

**Comment by XinyuuLi** [comment]
Thanks John. It has some problems also. The first problem is when 'from vasp import Vasp', it has a lot of errors, such as
 `Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 21, in <module>
    from .vasp_core import Vasp
SystemError: Parent module '' not loaded, cannot perform relative import'`
and 
`'Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 21, in <module>
    from . import vasp_core
SystemError: Parent module '' not loaded, cannot perform relative import`
This can be solved by delete the `.`. For example, change 'from . import vasp_core' to 'import vasp_core', change 'from .vasp_core import Vasp' into 'from vasp_core import Vasp'.
However, when I fix import problems, and try to run the script-19.py in dft-books, it generated errors1:
```
Traceback (most recent call last):
  File "/home/c3289/script/script.py", line 12, in <module>
    atoms=co)
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp_core.py", line 256, in __init__
    str(label), atoms)
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 627, in __init__
    atoms, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 279, in __init__
    self.read(restart)  # read parameters, atoms and results
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/readers.py", line 284, in read
    self.parameters.update(self.read_potcar())
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/readers.py", line 194, in read_potcar
    potcars += [lines[0].strip()]
IndexError: list index out of range
```
I checked the `readers.py`, and thought the problem should come form `lines = f.readlines()` did not read potcar. I have no idea with this, and comment out this code, then it came to the second error:
```
Traceback (most recent call last):
  File "/home/c3289/script/script.py", line 12, in <module>
    atoms=co)
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp_core.py", line 256, in __init__
    str(label), atoms)
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 627, in __init__
    atoms, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 279, in __init__
    self.read(restart)  # read parameters, atoms and results
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/readers.py", line 347, in read
    self.sort_atoms(atoms)
  File "/home/c3289/kitchin-python/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp_core.py", line 344, in sort_atoms
    pp = self.parameters['pp']
KeyError: 'pp'
```
Sorry for having so many problems. Do you think these errors were caused by the first error, functions are not imported properly?

**Comment by yqshao** [comment]
I guess you set `PYTHONPATH` to `/home/c3289/kitchin-python/vasp`, which could cause the first problem.
I think you are supposed to set it to the path of the repo, in this case,  `/home/c3289/kitchin-python`. And if you ran `setup.py`, it is not necessary to change the `PYTHONPATH`.

For problem 2, the first error might due to a empty `POTCAR`. Commenting that line out won't help. 
My guess is that you've generated a empty `POTCAR` when trying the code without setting `VASP_PP_PATH` (as what I did to reproduce the error).
You can try deleting the job folder and run the code again with a correct `VASP_PP_PATH`.

**Comment by XinyuuLi** [comment]
Thanks, Shao. I do set a wrong `PYTHONPATH`. The first problem was solved by changing it.
However, for problem 2, I have set `VASP_PP_PAPH` at the beginning. The problem came from I did not delete the empty POTCAR in `/molecule/simple-co`. When I rerun the script, the empty `POTCAR` by last run can not be overwrite.
Then, it comes to the third problem. 
`Traceback (most recent call last):
  File "script.py", line 12, in <module>
    atoms=co)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp_core.py", line 256, in __init__
    str(label), atoms)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 627, in __init__
    atoms, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 279, in __init__
    self.read(restart)  # read parameters, atoms and results
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp/readers.py", line 272, in read
    if self.get_state() == Vasp.NEB:
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp_core.py", line 765, in get_state
    self.get_db('jobid') is not None and
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/home/c3289/kitchin-python/vasp/vasp/getters.py", line 30, in get_db
    at = con.get(id=1)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/db/core.py", line 396, in get
    rows = list(self.select(selection, limit=2, **kwargs))
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/db/core.py", line 451, in select
    include_data=include_data):
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/db/sqlite.py", line 494, in _select
    self._initialize(con)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/db/sqlite.py", line 153, in _initialize
    'SELECT COUNT(*) FROM sqlite_master WHERE name="systems"')
sqlite3.OperationalError: disk I/O error`
Do you have any idea with this?

**Comment by XinyuuLi** [comment]
Besides, if I import the ase.calculators.Vasp module, it can work. The scritpt is:
`from ase import Atoms, Atom
from ase.calculators.vasp import Vasp
co = Atoms([Atom('C', [0, 0, 0]),
            Atom('O', [1.2, 0, 0])],
           cell=(6., 6., 6.))
calc = Vasp(prec='Accurate',  # output dir
            xc='pbe',  # the exchange-correlation functional
            nbands=6,    # number of bands
            encut=350,    # planewave cutoff
            ismear=1,    # Methfessel-Paxton smearing
            sigma=0.01)  # very small smearing factor for a molecule
co.set_calculator(calc)
print('energy = {0} eV'.format(co.get_potential_energy()))
print(co.get_forces())`
The return from terminal is:
`[c3289@rcglogin tests]$ python script.py
 running on    1 total cores
 distrk:  each k-point on    1 cores,    1 groups
 distr:  one band on    1 cores,    1 groups
 using from now: INCAR
 vasp.5.4.1 05Feb16 (build Jun 01 2016 13:32:26) complex

 POSCAR found :  2 types and       2 ions
 scaLAPACK will be used
 LDA part: xc-table for Pade appr. of Perdew
 POSCAR, INCAR and KPOINTS ok, starting setup
 FFT: planning ...
 WAVECAR not read
 entering main loop
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1     0.632151327317E+02    0.63215E+02   -0.28207E+03    12   0.851E+02
DAV:   2    -0.519243783968E+01   -0.68408E+02   -0.68408E+02    18   0.240E+02
DAV:   3    -0.148512150344E+02   -0.96588E+01   -0.96588E+01    12   0.977E+01
DAV:   4    -0.152840746699E+02   -0.43286E+00   -0.43344E+00    24   0.159E+01
DAV:   5    -0.152852548813E+02   -0.11802E-02   -0.60042E-03    12   0.768E-01    0.615E+00
DAV:   6    -0.148182490698E+02    0.46701E+00   -0.36393E+00    12   0.186E+01    0.351E+00
DAV:   7    -0.147178061278E+02    0.10044E+00   -0.57850E-01    18   0.784E+00    0.187E+00
DAV:   8    -0.146833368096E+02    0.34469E-01   -0.12142E-01    12   0.386E+00    0.354E-01
DAV:   9    -0.146836324358E+02   -0.29563E-03   -0.18756E-02    18   0.130E+00    0.159E-01
DAV:  10    -0.146839572788E+02   -0.32484E-03   -0.29009E-03    12   0.562E-01    0.348E-02
DAV:  11    -0.146848143463E+02   -0.85707E-03   -0.22570E-04     6   0.185E-01    0.159E-02
DAV:  12    -0.146850495442E+02   -0.23520E-03   -0.74355E-05     6   0.834E-02    0.916E-03
DAV:  13    -0.146845504219E+02    0.49912E-03   -0.41036E-05     6   0.695E-02    0.555E-03
DAV:  14    -0.146851381370E+02   -0.58772E-03   -0.85390E-06     6   0.328E-02    0.277E-03
DAV:  15    -0.146851409208E+02   -0.27838E-05   -0.52020E-06     6   0.243E-02
   1 F= -.14685141E+02 E0= -.14685141E+02  d E =0.199955E-11
 writing wavefunctions
energy = -14.68514092 eV
[[ 5.114725  0.       -0.      ]
 [-5.114725 -0.        0.      ]]`

**Comment by yqshao** [comment]
Hi, sorry for the delay. I did not get to test it since out cluster was down for several days. 

The problem seems to be caused by something related to sqlite3. 
The ase vasp calculator does not use sqlite3 database so it's not affected.

 I cannot reproduce your problem, but maybe you can try testing your sqlite3 installation and the python sqlite3 module with some simple operations to see  where it goes wrong.

**Comment by XinyuuLi** [comment]
Hi Shao. Thanks for your reply. As your guess, this problem did caused by sqlite3 in High Performance Computer. The HPC manager replied me this:
```
We run a parallel filesystem (lustre) on all of the nodes.
The database software sqlite is trying to lock the database file for exclusive access, and locking is not supported on the parallel filesystem. 
This is because to lock a file – it needs to communicate with the other 80 servers we have on the filesystem and make sure they are not locking the file too – so this would slow everything down.
The fix is:
1)	Edit the sqlite.py code – and remove references to locking when doing an open() to the file.
Or
2)	In your job script when it runs – copy all of the DB files to /tmp/…..  which is on the local node then access them there and if they do updates to the databases – when they are closed copy the DB files back to your home directory.
```
I checked the sqlite3 library. It is said: 
When a database is accessed by multiple connections, and one of the processes modifies the database, the SQLite database is locked until that transaction is committed. The `timeout` parameter specifies how long the connection should wait for the lock to go away until raising an exception. The default for the timeout parameter is 5.0 (five seconds).
According to this, I set `timeout` as 0, but it did not work. Do you have any suggestions about this problem?

**Comment by yqshao** [comment]
[It](https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible) seems that sqlite3 does not suit certain file systems and the combination will be risky. 

I know little about databases but it **might** be OK to skip locking so long as no cocurrency is involved. The database provided by ASE do have a `use_lock_file` parameter. You may try adding `use_lock_file=False` to each `connect` call of vasp and see if it works.

ASE also provides [three database backends](https://wiki.fysik.dtu.dk/ase/ase/db/db.html). So it could be possible to use another backend if that is supported by your file system (by changing the extension of database file in this vasp code).
