### ISSUE TITLE
Problems with VASP parallel computing

### ISSUE THREAD

**Issue by lixinyuu** [jkitchin/vasp#54]
I installed this package in HPC, and got problems to enable parallel VASP computing.
The script as below:
```
from ase import Atoms, Atom
from vasp import Vasp
from vasp.vasprc import VASPRC
import os
VASPRC['mode'] = 'run'
co = Atoms([Atom('C', [0, 0, 0]),
            Atom('O', [1.2, 0, 0])],
           cell=(6., 6., 6.))
calc = Vasp(path,  # output dir
            xc='pbe',    # the exchange-correlation functional
            nbands=6,    # number of bands
            encut=350,   # planewave cutoff
            ismear=1,    # Methfessel-Paxton smearing
            sigma=0.01,  # very small smearing factor for a molecule
            atoms=co)

print('energy = {0} eV'.format(co.get_potential_energy()))
```
This script works well when I use command 'python script.py' in terminal with output:
```
[c3289@rcglogin test_vasp]$ python script.py
energy = -14.69111507 eV
```
However, for some big systems, I have to use parallel VASP computing, so I write a bash script to submit this  python code. The bash script example as below, which called 4 cpus and 8gb memory:
```
#!/bin/bash

a=$(basename $(pwd))

cat <<END > $a.job
#!/bin/bash 
#PBS -N $a
#PBS -l select=1:ncpus=4:mem=8gb
#PBS -l walltime=168:00:00
#PBS -k eo

export OMP_NUM_THREADS=1
ulimit -s unlimited
ulimit -a
source ~/.bashrc
source /etc/profile.d/modules.sh
#module load mpi/intel
module load intel/mpi/64/5.1.3/2016.4.258
module load python/3.5.3

echo "Running vasp on 4 cpus" 

# now do it
cd \$PBS_O_WORKDIR
date
python script.py
date

END

#do it
qsub $a.job 
rm -f $a.job
```
However, when I run this bash script. It raise the error:
```
Running vasp on 4 cpus
Mon Mar 26 13:45:05 AEDT 2018
 Error reading item 'VCAIMAGES' from file INCAR.
Mon Mar 26 13:45:05 AEDT 2018
```
There were two reasons caused this:
1, Even though I have called 4 cpus in my bash script. The `NPROCS = len(open(os.environ['PBS_NODEFILE']).readlines())` in runner.py is 1.
2, When NPROCS ==1, and run VASP as in serial in 'runner.py', as：
```
if NPROCS == 1:
# no question. running in serial.
vaspcmd = VASPRC['vasp.executable.serial']
log.debug('NPROCS = 1. running in serial')
exitcode = os.system(vaspcmd)
return exitcode
```
It did not change the directory. So I added one line in front of line110 of `runner.py`, as:
```
if NPROCS == 1:
                # no question. running in serial.
                os.chdir(self.directory)
                vaspcmd = VASPRC['vasp.executable.serial']
                log.debug('NPROCS = 1. running in serial')
                exitcode = os.system(vaspcmd)
                return exitcode
```
And run the bash script again. The VASP do run, with output:
```
Running vasp on 1 cpus
Mon Mar 26 14:00:23 AEDT 2018
 running on    1 total cores
 distrk:  each k-point on    1 cores,    1 groups
 distr:  one band on    1 cores,    1 groups
 using from now: INCAR     
 vasp.5.4.1 05Feb16 (build Jun 01 2016 13:32:26) complex                        
  
 POSCAR found :  2 types and       2 ions
 scaLAPACK will be used
 LDA part: xc-table for Pade appr. of Perdew
 POSCAR, INCAR and KPOINTS ok, starting setup
 WARNING: small aliasing (wrap around) errors must be expected
 FFT: planning ...
 WAVECAR not read
 entering main loop
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1     0.632077036031E+02    0.63208E+02   -0.28209E+03    12   0.851E+02
DAV:   2    -0.519599844879E+01   -0.68404E+02   -0.68404E+02    18   0.240E+02
DAV:   3    -0.148556863982E+02   -0.96597E+01   -0.96597E+01    12   0.977E+01
DAV:   4    -0.152887386129E+02   -0.43305E+00   -0.43363E+00    24   0.160E+01
DAV:   5    -0.152899193761E+02   -0.11808E-02   -0.60097E-03    12   0.768E-01    0.615E+00
DAV:   6    -0.148236994071E+02    0.46622E+00   -0.36356E+00    12   0.186E+01    0.351E+00
DAV:   7    -0.147229862382E+02    0.10071E+00   -0.57723E-01    18   0.782E+00    0.187E+00
DAV:   8    -0.146888623570E+02    0.34124E-01   -0.12153E-01    12   0.386E+00    0.354E-01
DAV:   9    -0.146894442467E+02   -0.58189E-03   -0.18638E-02    18   0.130E+00    0.159E-01
DAV:  10    -0.146898345993E+02   -0.39035E-03   -0.29007E-03    12   0.559E-01    0.349E-02
DAV:  11    -0.146907869258E+02   -0.95233E-03   -0.24248E-04     6   0.187E-01    0.159E-02
DAV:  12    -0.146910295727E+02   -0.24265E-03   -0.81263E-05     6   0.853E-02    0.925E-03
DAV:  13    -0.146911150690E+02   -0.85496E-04   -0.43040E-05     6   0.710E-02
   1 F= -.14691115E+02 E0= -.14691115E+02  d E =0.344033E-11
Mon Mar 26 14:00:25 AEDT 2018
```
However, it ended with error:
```
Traceback (most recent call last):
  File "script.py", line 17, in <module>
    print('energy = {0} eV'.format(co.get_potential_energy()))
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/atoms.py", line 684, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 441, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 498, in get_property
    'calculation'.format(name))
ase.calculators.calculator.PropertyNotImplementedError: energy not present in this calculation
```
I thought it was came from the NPROS did not refer to the right called cpu numbers, so I commented lines 110-114, add `chdir` and `NPROS =4`, as below:
```
if NPROCS == 1:
                # no question. running in serial.
                # vaspcmd = VASPRC['vasp.executable.serial']
                # log.debug('NPROCS = 1. running in serial')
                # exitcode = os.system(vaspcmd)
                # return exitcode
            # else:
                # vanilla MPI run. multiprocessing does not work on more
                # than one node, and you must specify in VASPRC to use it
                if (VASPRC['queue.nodes'] > 1 or
                    (VASPRC['queue.nodes'] == 1 and
                     VASPRC['queue.ppn'] > 1 and
                     (VASPRC['multiprocessing.cores_per_process'] ==
                      'None'))):
                    os.chdir(self.directory)
                    NPROCS =4
                    s = 'queue.nodes = {0}'.format(VASPRC['queue.nodes'])
                    log.debug(s)
                    log.debug('queue.ppn = {0}'.format(VASPRC['queue.ppn']))
                    mpc = VASPRC['multiprocessing.cores_per_process']
                    log.debug('multiprocessing.cores_per_process'
                              '= {0}'.format(mpc))
                    log.debug('running vanilla MPI job')

                    log.debug('MPI NPROCS = {}'.format(NPROCS))
                    vaspcmd = VASPRC['vasp.executable.parallel']
                    parcmd = 'mpirun -np %i %s' % (NPROCS, vaspcmd)
                    exitcode = os.system(parcmd)
                    return exitcode
```
From the output, I could make sure that VASP were parallel running, as:
```
 running on    4 total cores
 distrk:  each k-point on    4 cores,    1 groups
 distr:  one band on    1 cores,    4 groups
 using from now: INCAR 
```
However, it still caused the error as:
```
Traceback (most recent call last):
  File "script.py", line 17, in <module>
    print('energy = {0} eV'.format(co.get_potential_energy()))
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/atoms.py", line 684, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 441, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/c3289/kitchin-python/vasp/vasp/vasp.py", line 41, in inner
    return func(self, *args, **kwargs)
  File "/cm/software/apps/python/3.5.3/lib/python3.5/site-packages/ase/calculators/calculator.py", line 498, in get_property
    'calculation'.format(name))
ase.calculators.calculator.PropertyNotImplementedError: energy not present in this calculation
```
Can any one give me some suggestions on this problem?

**Comment by jkitchin** [comment]
This sounds similar to https://github.com/jkitchin/vasp/issues/39 and might be related to the ase version. I also see you are running python3. The main branch is only compatible with python2. I am not sure if it works well with Python3 yet. I am currently on sabbatical away from the cluster where I could work on this, so it will be a while before it gets fixed.
